version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    image: the_shortest_url_local_django
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
    ports:
      - "8000:8000"
    command: /start.sh

