version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./docker/test/django/Dockerfile
    image: the_shortest_url_test_django
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.test/.django
    command: /start.sh
